env:
  browser: true
  commonjs: true
  jest: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  consistent-return: 2
  indent: [1,2]
  no-else-return: 1
  semi: [1, "always"]
  space-unary-ops: 2
